name: 'Install Vulkan'
description: 'Vulkan installation procedure for github actions'

branding:
  icon: 'play'
  color: 'red'

inputs: 
  vulkan_version:
    description: 'Vulkan sdk version'
    default: ''
    required: false
  vulkan_components:
    description: 'Which Vulkan sdk`s components to install'
    default: Vulkan_Headers, Vulkan_Loader
    required: true

runs:
  using: "composite"
  steps:
    - name: Resolve Vulkan SDK Configuration
      shell: bash
      run: |
        ./.github/action_helpers.sh
        