// DO NOT INCLUDE THIS FILE FROM ANY FILES OTHER THAN MESHLET CONFIG FILE
const int MAX_VERTEX_COUNT = 64;
const int MAX_PRIMITIVE_COUNT = MAX_VERTEX_COUNT * 2 - 2;
const int MAX_PRIMITIVE_INDICES_COUNT = MAX_PRIMITIVE_COUNT * 3;
const int MAX_TASK_COUNT = 32;
const int MESHLET_PER_TASK = 32;
const int GROUP_SIZE = 32;